version: '2'

services:

  atsd:
    image: axibase/atsd:latest
    ports:
      - "8088:8088"
      - "8443:8443"
      - "8081:8081"
      - "8082:8082/udp"
    container_name: atsd
    hostname: atsd
    restart: always
    environment:
      - COLLECTOR_USER_NAME=${USER}
      - COLLECTOR_USER_PASSWORD=${PASSWORD}
  collector:
    image: axibase/collector:latest
    depends_on:
      - atsd
    ports:
      - "9443:9443"
    container_name: axibase-collector
    restart: always
    environment:
      - COLLECTOR_ARGS=-atsd-url=https://${USER}:${PASSWORD}@atsd:8443 -job-path=https://raw.githubusercontent.com/axibase/axibase-collector-docs/master/job-templates/socrata-cdc.xml -job-execute=socrata-cdc
      - JAVA_OPTS=-Xmx2g